version: "2.0"
services:
  event-api:
    build: .
    environment:
      - MONGO_HOST=mongo
    container_name: event-api
    restart: always
    ports:
      - "8181:8181"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net
  mongo:
    image: mongo:4.2.10
    restart: always
    container_name: events-mongodb
    hostname: mongo
    volumes:
      - $HOME/mongo:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: "exit 0"
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge